version: '3.8'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-api
    container_name: laravel-api-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel-api-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: laravel-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: qa_assessment
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  # Redis Service
  redis:
    image: redis:7-alpine
    container_name: laravel-api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel-network

# Networks
networks:
  laravel-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
