name: Laravel project

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, pdo_mysql, bcmath, soap, intl, gd
        coverage: xdebug

    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader
      working-directory: laravel-project

    - name: Setup Environment
      run: |
        cp .env.example .env
        php artisan key:generate
        php -r "
          file_put_contents('.env', str_replace(
            ['DB_CONNECTION=mysql', 'DB_DATABASE=qa_assessment'],
            ['DB_CONNECTION=sqlite', 'DB_DATABASE=:memory:'],
            file_get_contents('.env')
          ));
        "
        php artisan config:clear
        php artisan cache:clear
      working-directory: laravel-project

    - name: Directory Permissions
      run: chmod -R 775 storage bootstrap/cache
      working-directory: laravel-project

    - name: Run Migrations
      run: php artisan migrate --force
      working-directory: laravel-project

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
      working-directory: laravel-project
